In [355]:
import pandas as pd
import numpy as np
import seaborn as sns

# PREPROCESSING MODULES
from sklearn.model_selection import train_test_split

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.base import BaseEstimator, TransformerMixin

from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.impute import SimpleImputer

from sklearn.decomposition import PCA

# CLASSIFIER MODULES
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# METRIC MODULES
from sklearn.metrics import f1_score, recall_score, precision_score, fbeta_score, confusion_matrix



ModuleNotFoundError: No module named 'xgboost'

In [353]:
df = pd.read_csv('data/combined_cleaned.csv')
df['genres'] = df['genres'].str.split(', ')
df['tags'] = df['tags'].str.split(', ')
df['platforms'] = df['platforms'].str.split(', ')
df['categories'] = df['categories'].str.split(', ')
df['supported_languages'] = df['supported_languages'].str.split(', ')



# df['target'] = (df['average_2weeks'] > 500).astype(int)

df['target'] = (df['hours_over_age'] >= 1).astype(int)


X_train, X_test, y_train, y_test = train_test_split(df[['supported_languages','tags','genres','categories','platforms',
                                                        'historic_developer_average_recommendations','historic_developer_average_owners','historic_developer_average_hours',
                                                        'historic_publisher_average_recommendations','historic_publisher_average_owners','historic_publisher_average_hours'
                                                       ]], df['target'], test_size=0.2,random_state=42)
X_train

supported_languages  \
17474  [English, Russian, French, German, Spanish - S...   
41124  [English, German, Italian, Japanese, Korean, P...   
11605                                          [English]   
29502                                          [English]   
12311                                          [Russian]   
...                                                  ...   
6265   [English, French, German, Spanish - Spain, Rus...   
11284                                [English, Japanese]   
38158                                          [English]   
860                           [English, Russian, German]   
15795                                          [English]   

                                                    tags  \
17474  [Action, Indie, Adventure, Singleplayer, Dark ...   
41124  [Local Co-Op, Physics, Cute, Puzzle, Family Fr...   
11605  [Football, Simulation, Sports, Strategy, Manag...   
29502                         [Indie, Casual, Adventure]   
12311  [Casual, Indie, Memes, Psychological Horror, C...   
...                                                  ...   
6265           [Sports, Indie, Bikes, BMX, Singleplayer]   
11284                   [Action, Indie, Casual, Classic]   
38158  [Horror, Pixel Graphics, Hand-drawn, Dog, Top-...   
860     [Strategy, Simulation, World War II, Tanks, RTS]   
15795  [Early Access, JRPG, Choose Your Own Adventure...   

                                                  genres  \
17474                         [Action, Adventure, Indie]   
41124                                            [Indie]   
11605                               [Simulation, Sports]   
29502                         [Adventure, Casual, Indie]   
12311                                    [Casual, Indie]   
...                                                  ...   
6265                                     [Indie, Sports]   
11284                            [Action, Casual, Indie]   
38158                                            [Indie]   
860                               [Simulation, Strategy]   
15795  [Action, Adventure, Casual, Indie, Massively M...   

                                              categories  \
17474  [Single-player, Steam Achievements, Full contr...   
41124  [Single-player, Multi-player, Co-op, Shared/Sp...   
11605  [Single-player, Multi-player, PvP, Shared/Spli...   
29502                                    [Single-player]   
12311               [Single-player, Steam Trading Cards]   
...                                                  ...   
6265   [Single-player, Steam Achievements, Full contr...   
11284  [Single-player, Steam Achievements, Full contr...   
38158                [Single-player, Steam Achievements]   
860    [Single-player, Multi-player, Steam Cloud, Inc...   
15795  [Multi-player, MMO, Co-op, Online Co-op, Cross...   

                   platforms  historic_developer_average_recommendations  \
17474              [windows]                                         0.0   
41124              [windows]                                         0.0   
11605  [windows, mac, linux]                                         0.0   
29502              [windows]                                         0.0   
12311              [windows]                                         0.0   
...                      ...                                         ...   
6265               [windows]                                         0.0   
11284              [windows]                                         0.0   
38158              [windows]                                         0.0   
860                [windows]                                      1127.5   
15795       [windows, linux]                                         0.0   

       historic_developer_average_owners  historic_developer_average_hours  \
17474                            20000.0                               0.0   
41124                                0.0                               0.0   
11605 

In [300]:
class MultiHotEncoder(BaseEstimator, TransformerMixin):
    """Wraps `MultiLabelBinarizer` in a form that can work with `ColumnTransformer`. Note
    that input X has to be a `pandas.DataFrame`.
    """
    def __init__(self):
        self.mlbs = list()
        self.n_columns = 0
        self.categories_ = self.classes_ = list()

    def fit(self, X:pd.DataFrame, y=None):
        for i in range(X.shape[1]): # X can be of multiple columns
            mlb = MultiLabelBinarizer()
            mlb.fit(X.iloc[:,i])
            self.mlbs.append(mlb)
            self.classes_.append(mlb.classes_)
            self.n_columns += 1
        return self

    def transform(self, X:pd.DataFrame):
        if self.n_columns == 0:
            raise ValueError('Please fit the transformer first.')
        if self.n_columns != X.shape[1]:
            raise ValueError(f'The fit transformer deals with {self.n_columns} columns '
                             f'while the input has {X.shape[1]}.'
                            )
        result = list()
        for i in range(self.n_columns):
            result.append(self.mlbs[i].transform(X.iloc[:,i]))

        result = np.concatenate(result, axis=1)
        return result

In [357]:
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
#     ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('multihot', MultiHotEncoder())
])

tag_transformer = Pipeline(steps=[
    ('multihot', MultiHotEncoder()),
    ('pca', PCA(100))
])

numeric_features = X_train.select_dtypes(include=['int64', 'float64']).columns
print('numeric_features',numeric_features)
categorical_features = X_train.select_dtypes(include=['object']).columns
print('categorical_features',categorical_features)
# try:
#     tag_features = X_train[['tags']].columns
# except:
#     tag_features = []
# print('tags',tag_features)


preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features),
#         ('tag', tag_transformer, tag_features)
    ])

rf = Pipeline(steps=[('preprocessor', preprocessor),
                      ('classifier', RandomForestClassifier(1000,max_features=100,class_weight={1: 10, 0: 1}))])

xg = Pipeline(steps=[('preprocessor', preprocessor),
                      ('classifier', RandomForestClassifier(1000,class_weight={1: 10, 0: 1}))])



numeric_features Index(['historic_developer_average_recommendations',
       'historic_developer_average_owners', 'historic_developer_average_hours',
       'historic_publisher_average_recommendations',
       'historic_publisher_average_owners',
       'historic_publisher_average_hours'],
      dtype='object')
categorical_features Index(['supported_languages', 'tags', 'genres', 'categories', 'platforms'], dtype='object')


In [307]:
rf.fit(X_train,y_train)
y_predict = rf.predict(X_test)
print('precision: ', precision_score(y_test,y_predict))
print('recall: ', recall_score(y_test,y_predict))
print('f1 :', f1_score(y_test, y_predict))
np.sum(y_predict)

/Users/matteofortier/opt/anaconda3/lib/python3.8/site-packages/sklearn/preprocessing/_label.py:994: UserWarning: unknown class(es) ['Mods'] will be ignored
  warnings.warn('unknown class(es) {0} will be ignored'


precision:  0.9375
recall:  0.06382978723404255
f1 : 0.1195219123505976


16

In [334]:
rf.fit(X_train,y_train)
y_predict = rf.predict(X_test)
print('precision: ', precision_score(y_test,y_predict))
print('recall: ', recall_score(y_test,y_predict))
print('f1 :', f1_score(y_test, y_predict))
print(confusion_matrix(y_test, y_predict))
print(X_train.columns)

precision:  0.6923076923076923
recall:  0.03435114503816794
f1 : 0.06545454545454546
[[8073    4]
 [ 253    9]]
Index(['tags', 'genres', 'categories', 'platforms',
       'historic_developer_average_owners',
       'historic_developer_average_hours'],
      dtype='object')


In [341]:
rf.fit(X_train,y_train)
y_predict = rf.predict(X_test)
print('precision: ', precision_score(y_test,y_predict))
print('recall: ', recall_score(y_test,y_predict))
print('f1 :', f1_score(y_test, y_predict))
print(confusion_matrix(y_test, y_predict))
print(X_train.columns)

precision:  0.6666666666666666
recall:  0.007633587786259542
f1 : 0.015094339622641508
[[8076    1]
 [ 260    2]]
Index(['tags', 'genres', 'categories', 'platforms',
       'historic_developer_average_owners',
       'historic_developer_average_hours'],
      dtype='object')


In [343]:
rf.fit(X_train,y_train)
y_predict = rf.predict(X_test)
print('precision: ', precision_score(y_test,y_predict))
print('recall: ', recall_score(y_test,y_predict))
print('f1 :', f1_score(y_test, y_predict))
print(confusion_matrix(y_test, y_predict))
print(X_train.columns)

precision:  0.5
recall:  0.003816793893129771
f1 : 0.007575757575757576
[[8076    1]
 [ 261    1]]
Index(['owners', 'tags', 'genres', 'categories', 'platforms',
       'historic_developer_average_owners',
       'historic_developer_average_hours'],
      dtype='object')


In [358]:
rf.fit(X_train,y_train)
y_predict = rf.predict(X_test)
print('precision: ', precision_score(y_test,y_predict))
print('recall: ', recall_score(y_test,y_predict))
print('f1 :', f1_score(y_test, y_predict))
print(confusion_matrix(y_test, y_predict))
print(X_train.columns)

/Users/matteofortier/opt/anaconda3/lib/python3.8/site-packages/sklearn/preprocessing/_label.py:994: UserWarning: unknown class(es) ['English (full audio)', 'Italian \r\n\r\n[b][/b] languages with full audio support'] will be ignored
  warnings.warn('unknown class(es) {0} will be ignored'
/Users/matteofortier/opt/anaconda3/lib/python3.8/site-packages/sklearn/preprocessing/_label.py:994: UserWarning: unknown class(es) ['Accounting'] will be ignored
  warnings.warn('unknown class(es) {0} will be ignored'


precision:  0.5526315789473685
recall:  0.08936170212765958
f1 : 0.15384615384615385
[[8081   17]
 [ 214   21]]
Index(['supported_languages', 'tags', 'genres', 'categories', 'platforms',
       'historic_developer_average_recommendations',
       'historic_developer_average_owners', 'historic_developer_average_hours',
       'historic_publisher_average_recommendations',
       'historic_publisher_average_owners',
       'historic_publisher_average_hours'],
      dtype='object')
